name: CI/CD Frontend VidalCasino

on:
  push:
    branches: [ deploy ]

jobs:
  test:
    name: Pruebas Unitarias
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar y Testear
        run: |
          npm install
          npm test -- --watch=false --browsers=ChromeHeadless

  deploy:
    name: Build, Push y Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build y Push
        run: |
          docker build -t 605493908341.dkr.ecr.us-east-1.amazonaws.com/casino-frontend:latest .
          docker push 605493908341.dkr.ecr.us-east-1.amazonaws.com/casino-frontend:latest
      - name: Deploy EKS
        run: |
          aws eks update-kubeconfig --name vidalcasino-cluster --region us-east-1
          kubectl apply -f deployment.yaml
          kubectl rollout restart deployment/casino-frontend