name: CI/CD Pipeline - Frontend Casino

on:
  push:
    branches:
      - deploy 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials (AWS Academy)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Start Docker Daemon
      run: sudo systemctl start docker

    - name: Build, Tag and Push Image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        VERSION_TAG="v1.0.0"
        REPO_NAME="casino-frontend"
        export DOCKER_BUILDKIT=1
        
        docker build -t $ECR_REGISTRY/$REPO_NAME:${{ github.sha }} \
                     -t $ECR_REGISTRY/$REPO_NAME:latest \
                     -t $ECR_REGISTRY/$REPO_NAME:$VERSION_TAG .
        
        docker push $ECR_REGISTRY/$REPO_NAME:${{ github.sha }}
        docker push $ECR_REGISTRY/$REPO_NAME:latest
        docker push $ECR_REGISTRY/$REPO_NAME:$VERSION_TAG

    - name: Update Kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Deploy Manifests to EKS Cluster
      run: |
        sed -i "s|IMAGEN_MUTABLE|$ECR_REGISTRY/$REPO_NAME:${{ github.sha }}|g" deployment.yaml

        kubectl apply -f deployment.yaml
        
        kubectl rollout restart deployment/casino-frontend